url: http://hipsterveggies.com/
baseurl: http://hipsterveggies.com/

# Site settings
title: Hipster Veggies
email: hello@hipsterveggies.com
description: "intelligent locally-grown subculture"


# Team names, titles and social links
people:
- name: Jasmine Dumas
  pic: jasmine_pic
  position: Chief Grower
  social:
    - title: twitter
      url: https://twitter.com/jasdumas


- name: Jenna Daly
  pic: 2
  position: Chief Grower
  social:
    - title: twitter
      url: https://twitter.com/jennamdaly


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/hipsterveggies


# Postal address (add as many lines as necessary)
address:
  - line: 

# Build settings
markdown: kramdown
permalink: pretty
